import { QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";

import "@/styles/globals.css";
import DashboardLayout from "@/components/layouts/DashboardLayout";
import queryClient from "@/lib/api/queryClient";

import type { AppProps } from "next/app";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <DashboardLayout>
          <Component {...pageProps} />
        </DashboardLayout>
      </QueryClientProvider>
    </>
  );
}
